app/Http/routes.php
<?php

Route::get('/', 'StaticController@index');
Route::resource('academy', 'AcademyController');
Route::resource('explore', 'ExploreController',['only' => [
    'index', 'show'
]]);

app/Academy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Academy extends Model
{
    protected $fillable = [
        'username',
        'email',
        'phone',
        'academy_name',
        'image',
        'description',
        'latitude',
        'longitude'
    ];

    protected $casts = [
        'latitude' => 'float',
        'longitude' => 'float'
    ];

    public function tags()
    {
        return $this->hasMany(AcademyTag::class);
    }

    public function timeSlots()
    {
        return $this->hasMany(AcademyTimeSlot::class);
    }
}

app/AcademyTag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AcademyTag extends Model
{
    protected $fillable = ['tag_name'];
}

app/AcademyTimeSlot.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AcademyTimeSlot extends Model
{
    protected $fillable = ['day_of_week', 'time_slot'];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AcademyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Academy;
use App\AcademyTimeSlot;
use App\AcademyTag;
use File;

class AcademyController extends Controller
{
    public function index()
    {
        $academies = Academy::orderBy('created_at', 'desc')
            ->get();

        return view('academy.index', [
            'title' => 'Manage Academy',
            'academies' => $academies
        ]);
    }

    public function create()
    {
        return view('academy.create', [
            'title' => 'Create Academy'
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'username' => 'required|alpha_num|between:5,255|unique:academies',
            'email' => 'required|email|max:255',
            'phone' => 'required|max:255',
            'academy_name' => 'required|max:255',
            'image' => 'required|image|max:2000',
            'description' => 'required|max:2000',
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
            'tags' => 'required|array',
            'time_slots.*' => 'max:255'
        ]);

        $imageName = null;

        if($request->hasFile('image')) {
            $imageName = str_random(16).'.'.$request->file('image')->getClientOriginalExtension();
            $request->file('image')->move(public_path('uploads'), $imageName);
        }

        $academy = Academy::create([
            'username' => $request->username,
            'email' => $request->email,
            'phone' => $request->phone,
            'academy_name' => $request->academy_name,
            'image' => $imageName,
            'description' => $request->description,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude
        ]);

        $slots = [];

        foreach($request->get('time_slots') as $key => $timeSlot) {
            $slots[] = new AcademyTimeSlot([
                'day_of_week' => $key,
                'time_slot' => $timeSlot
            ]);
        }

        $tags = [];

        foreach($request->get('tags') as $tag) {
            $tags[] = new AcademyTag([
                'tag_name' => $tag
            ]);
        }

        $academy->tags()->saveMany($tags);
        $academy->timeSlots()->saveMany($slots);

        return redirect()
            ->route('academy.index')
            ->withMessage('Successfully create Academy!');
    }

    public function show(Academy $academy)
    {
        return view('academy.show', [
            'title' => 'View Academy',
            'academy' => $academy
        ]);
    }

    public function edit(Academy $academy)
    {
        return view('academy.edit', [
            'title' => 'Edit Academy',
            'academy' => $academy
        ]);
    }

    public function update(Academy $academy, Request $request)
    {
        $this->validate($request, [
            'username' => 'required|alpha_num|between:5,255|unique:academies,username,'.$academy->id,
            'email' => 'required|email|max:255',
            'phone' => 'required|max:255',
            'academy_name' => 'required|max:255',
            'image' => 'image|max:2000',
            'description' => 'required|max:2000',
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
            'tags' => 'required|array',
            'time_slots.*' => 'max:255'
        ]);

        $imageName = $academy->image;

        if($request->hasFile('image')) {
            File::delete(public_path('uploads/'.$academy->image));
            $imageName = str_random(16).'.'.$request->file('image')->getClientOriginalExtension();
            $request->file('image')->move(public_path('uploads'), $imageName);
        }

        $academy->update([
            'username' => $request->username,
            'email' => $request->email,
            'phone' => $request->phone,
            'academy_name' => $request->academy_name,
            'image' => $imageName,
            'description' => $request->description,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude
        ]);

        $academy->tags()->delete();
        $tags = [];

        foreach($request->get('tags') as $tag) {
            $tags[] = new AcademyTag([
                'tag_name' => $tag
            ]);
        }

        $academy->load('timeSlots');

        $slots = [];

        foreach($request->get('time_slots') as $key => $timeSlot) {

            if($current = $academy->timeSlots->where('day_of_week', $key)->first()) {
                $current->time_slot = $timeSlot;
                $current->save();
            }
        }

        $academy->tags()->saveMany($tags);

        return redirect()
            ->route('academy.index')
            ->withMessage('Successfully updated Academy!');
    }

    public function destroy(Academy $academy)
    {
        File::delete(public_path('uploads/'.$academy->image));
        $academy->tags()->delete();
        $academy->timeSlots()->delete();
        $academy->delete();

        return redirect()
            ->route('academy.index')
            ->withMessage('Successfully deleted Academy!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExploreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Academy;
use Mail;

class ExploreController extends Controller
{
    public function index()
    {
        $academies = Academy::get(['id', 'academy_name', 'image', 'latitude', 'longitude'])
            ->toJson();
        return view('explore.index', [
            'title' => 'Explore Academies',
            'academies' => $academies
        ]);
    }

    public function show($id)
    {
        $academy = Academy::findOrFail($id);

        Mail::queue('emails.visit', ['academy' => $academy], function ($m) use ($academy) {
            $m->from('sandbox@sparkpostbox.com', 'Your Application');

            $m->to(env('ADMIN_EMAIL'), 'Assignment')->subject($academy->academy_name.' have a new Vistor!');
        });

        return view('explore.show', [
            'title' => 'Explore '.$academy->academy_name,
            'academy' => $academy
        ]);
    }
}

app/Http/Controllers/StaticController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class StaticController extends Controller
{
    public function index()
    {
        return view('static.index', [
            'title' => 'Assignment'
        ]);
    }
}

resources/views/academy/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="panel-title">Create Academy</p>
        </div>
        <div class="panel-body">
            <form action="{{route('academy.store')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <h1>Basic Information</h1>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" name="username" value="{{old('username')}}" class="form-control">
                            @if($errors->has('username'))
                                <p class="text-danger">{{$errors->first('username')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Email Address</label>
                            <input type="text" name="email" class="form-control">
                            @if($errors->has('email'))
                                <p class="text-danger">{{$errors->first('email')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Telephone</label>
                            <input type="text" name="phone" class="form-control">
                            @if($errors->has('phone'))
                                <p class="text-danger">{{$errors->first('phone')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>Academy Name</label>
                            <input type="text" name="academy_name" class="form-control">
                            @if($errors->has('academy_name'))
                                <p class="text-danger">{{$errors->first('academy_name')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Upload Image</label>
                            <input type="file" name="image" class="form-control">
                            @if($errors->has('image'))
                                <p class="text-danger">{{$errors->first('image')}}</p>
                            @endif
                        </div>
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label>Latitude</label>
                                <input type="text" name="latitude" class="form-control">
                                @if($errors->has('latitude'))
                                    <p class="text-danger">{{$errors->first('latitude')}}</p>
                                @endif
                            </div>
                            <div class="col-sm-6 form-group">
                                <label>Longitude</label>
                                <input type="text" name="longitude" class="form-control">
                                @if($errors->has('longitude'))
                                    <p class="text-danger">{{$errors->first('longitude')}}</p>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="description" class="form-control"></textarea>
                            @if($errors->has('description'))
                                <p class="text-danger">{{$errors->first('description')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Tags</label>

                            <div class="select-box clearfix form-control">
                                <span v-for="tag in selected" track-by="$index" class="select-box-item label label-info">
                                    <input type="hidden" name="tags[@{{$index}}]" :value="tag">
                                    @{{tag}}
                                    <span @click="remove(tag)">&times;</span>
                                </span>
                                <input type="text" class="select-input" v-model="tag_input" @keyup.delete="clear" @keyup.space="add">
                            </div>
                            @if($errors->has('tags'))
                                <p class="text-danger">{{$errors->first('tags')}}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <h2>Time Slots</h2>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Sunday</label>
                            <input type="text" name="time_slots[sunday]" class="form-control">
                            @if($errors->has('time_slots.sunday'))
                                <p class="text-danger">{{$errors->first('time_slots.sunday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Monday</label>
                            <input type="text" name="time_slots[monday]" class="form-control">
                            @if($errors->has('time_slots.monday'))
                                <p class="text-danger">{{$errors->first('time_slots.monday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Tuesday</label>
                            <input type="text" name="time_slots[tuesday]" class="form-control">
                            @if($errors->has('time_slots.tuesday'))
                                <p class="text-danger">{{$errors->first('time_slots.tuesday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Wednesday</label>
                            <input type="text" name="time_slots[wednesday]" class="form-control">
                            @if($errors->has('time_slots.wednesday'))
                                <p class="text-danger">{{$errors->first('time_slots.wednesday')}}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Thursday</label>
                            <input type="text" name="time_slots[thursday]" class="form-control">
                            @if($errors->has('time_slots.thursday'))
                                <p class="text-danger">{{$errors->first('time_slots.thursday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Friday</label>
                            <input type="text" name="time_slots[friday]" class="form-control">
                            @if($errors->has('time_slots.friday'))
                                <p class="text-danger">{{$errors->first('time_slots.friday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Saturday</label>
                            <input type="text" name="time_slots[saturday]" class="form-control">
                            @if($errors->has('time_slots.saturday'))
                                <p class="text-danger">{{$errors->first('time_slots.saturday')}}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create Academy" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
@stop

@section('scripts')
    <script type="text/javascript">
        window.import = {
            tags: {!! json_encode(old('tags', [])) !!}
        };
    </script>
    <script type="text/javascript" src="{{asset('js/create.js')}}"></script>
@stop

resources/views/academy/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="panel-title">
            Create Academy
            <a href="{{route('academy.show', $academy)}}" class="pull-right">View</a>
            </p>
        </div>
        <div class="panel-body">
            <form action="{{route('academy.update', $academy)}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="PUT">
                <h1>Basic Information</h1>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" name="username" value="{{old('username', $academy->username)}}" class="form-control">
                            @if($errors->has('username'))
                                <p class="text-danger">{{$errors->first('username')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Email Address</label>
                            <input type="text" name="email" value="{{old('email', $academy->email)}}" class="form-control">
                            @if($errors->has('email'))
                                <p class="text-danger">{{$errors->first('email')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Telephone</label>
                            <input type="text" name="phone" value="{{old('phone', $academy->phone)}}" class="form-control">
                            @if($errors->has('phone'))
                                <p class="text-danger">{{$errors->first('phone')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>Academy Name</label>
                            <input type="text" name="academy_name" value="{{old('academy_name', $academy->academy_name)}}" class="form-control">
                            @if($errors->has('academy_name'))
                                <p class="text-danger">{{$errors->first('academy_name')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Upload Image <small class="text-info">Optional</small></label>
                            <input type="file" name="image" class="form-control">
                            @if($errors->has('image'))
                                <p class="text-danger">{{$errors->first('image')}}</p>
                            @endif
                        </div>
                        <div class="row">
                            <div class="col-sm-6 form-group">
                                <label>Latitude</label>
                                <input type="text" name="latitude" value="{{old('latitude', $academy->latitude)}}" class="form-control">
                                @if($errors->has('latitude'))
                                    <p class="text-danger">{{$errors->first('latitude')}}</p>
                                @endif
                            </div>
                            <div class="col-sm-6 form-group">
                                <label>Longitude</label>
                                <input type="text" name="longitude" value="{{old('longitude', $academy->longitude)}}" class="form-control">
                                @if($errors->has('longitude'))
                                    <p class="text-danger">{{$errors->first('longitude')}}</p>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="description" class="form-control">{{old('description', $academy->description)}}</textarea>
                            @if($errors->has('description'))
                                <p class="text-danger">{{$errors->first('description')}}</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Tags</label>

                            <div class="select-box clearfix form-control">
                                <span v-for="tag in selected" track-by="$index" class="select-box-item label label-info">
                                    <input type="hidden" name="tags[@{{$index}}]" :value="tag">
                                    @{{tag}}
                                    <span @click="remove(tag)">&times;</span>
                                </span>
                                <input type="text" class="select-input" v-model="tag_input" @keyup.delete="clear" @keyup.space="add">
                            </div>
                            @if($errors->has('tags'))
                                <p class="text-danger">{{$errors->first('tags')}}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <h2>Time Slots</h2>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Sunday</label>
                            <input type="text" name="time_slots[sunday]" value="{{old('time_slots.sunday', $academy->timeSlots->where('day_of_week', 'sunday')->first()->time_slot)}}" class="form-control">
                            @if($errors->has('time_slots.sunday'))
                                <p class="text-danger">{{$errors->first('time_slots.sunday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Monday</label>
                            <input type="text" name="time_slots[monday]" value="{{old('time_slots.monday', $academy->timeSlots->where('day_of_week', 'monday')->first()->time_slot)}}" class="form-control">
                            @if($errors->has('time_slots.monday'))
                                <p class="text-danger">{{$errors->first('time_slots.monday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Tuesday</label>
                            <input type="text" name="time_slots[tuesday]" value="{{old('time_slots.tuesday', $academy->timeSlots->where('day_of_week', 'tuesday')->first()->time_slot)}}" class="form-control">
                            @if($errors->has('time_slots.tuesday'))
                                <p class="text-danger">{{$errors->first('time_slots.tuesday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Wednesday</label>
                            <input type="text" name="time_slots[wednesday]" value="{{old('time_slots.wednesday', $academy->timeSlots->where('day_of_week', 'wednesday')->first()->time_slot)}}" class="form-control">
                            @if($errors->has('time_slots.wednesday'))
                                <p class="text-danger">{{$errors->first('time_slots.wednesday')}}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Thursday</label>
                            <input type="text" name="time_slots[thursday]" value="{{old('time_slots.thursday', $academy->timeSlots->where('day_of_week', 'thursday')->first()->time_slot)}}" class="form-control">
                            @if($errors->has('time_slots.thursday'))
                                <p class="text-danger">{{$errors->first('time_slots.thursday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Friday</label>
                            <input type="text" name="time_slots[friday]" value="{{old('time_slots.friday', $academy->timeSlots->where('day_of_week', 'friday')->first()->time_slot)}}" class="form-control">
                            @if($errors->has('time_slots.friday'))
                                <p class="text-danger">{{$errors->first('time_slots.friday')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Saturday</label>
                            <input type="text" name="time_slots[saturday]" value="{{old('time_slots.saturday', $academy->timeSlots->where('day_of_week', 'saturday')->first()->time_slot)}}" class="form-control">
                            @if($errors->has('time_slots.saturday'))
                                <p class="text-danger">{{$errors->first('time_slots.saturday')}}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update Academy" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
@stop

@section('scripts')
    <script type="text/javascript">
        window.import = {
            tags: {!! json_encode($academy->tags->lists('tag_name')) !!}
        };
    </script>
    <script type="text/javascript" src="{{asset('js/create.js')}}"></script>
@stop

resources/views/academy/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="panel-title">
                Manage Academies
                <a href="{{route('academy.create')}}" class="pull-right">Create Academy</a>
            </p>

        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Academy Name</th>
                                <th>Email Address</th>
                                <th>Telephone</th>
                                <th colspan="4">Created</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($academies as $academy)
                                <tr>
                                    <td>{{$academy->academy_name}}</td>
                                    <td>{{$academy->email}}</td>
                                    <td>{{$academy->phone}}</td>
                                    <td>{{$academy->created_at->diffForHumans()}}</td>
                                    <td><a href="{{route('academy.edit', $academy)}}">Edit</a></td>
                                    <td><a href="{{route('academy.show', $academy)}}">View</a></td>
                                    <td>
                                        <form action="{{route('academy.destroy', $academy)}}"
                                            onsubmit="return confirm('Are you sure?')"
                                            method="post" class="form-inline">
                                            <input type="hidden" name="_method" value="delete">
                                            {{csrf_field()}}
                                            <input type="submit" value="Delete" class="btn-delete">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>{{$title}}</title>
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">
    <meta name="viewport" content="initial-scale=1.0">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Assignment</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{route('explore.index')}}">Explore</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{route('academy.index')}}">Manage Academy</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @if(session()->has('message'))
            <div class="alert alert-info">
                {{session()->get('message')}}
            </div>
        @endif
        @yield('content')
    </div>
    @yield('scripts')
</body>
</html>